### ISSUE TITLE
Bug: monthsperyeararr - ?

### ISSUE THREAD

**Issue by tremendus** [IonicaBizau/hebrew-date#12]
https://github.com/IonicaBizau/hebrew-date/blob/c7c236b99ad5a0f294c34dd4584a5a6d4e8d1faa/lib/index.js#L103

In this counting sequence, shouldn't 12 come after 11? ... rather than 8 !

Don't think it would cause a bug unless you changed the sequence of # months in a year, which you can't logically do, because both argument/param values 8 and 12 equals 12. 

Still ...

**Comment by IonicaBizau** [comment]
Oh, that's a good point! You're right!

**Comment by IonicaBizau** [comment]
Addressed. Thanks!
